import React, { useState } from 'react';
import { BlockMath, InlineMath } from 'react-katex';
import 'katex/dist/katex.min.css';
import TheoremBlock from '../../../components/content/TheoremBlock.jsx';
import DefinitionBlock from '../../../components/content/DefinitionBlock.jsx';
import ExampleBlock from '../../../components/content/ExampleBlock.jsx';
import WarningBlock from '../../../components/content/WarningBlock.jsx';
import PythonCode from '../../../components/content/PythonCode.jsx';

function SigmaAlgebraViz() {
  const [selected, setSelected] = useState(new Set(['A']));

  // Universe Omega = {1,2,3,4,5,6} (die roll)
  const omega = [1, 2, 3, 4, 5, 6];
  const A = new Set([1, 2, 3]);
  const B = new Set([2, 3, 4]);
  const Ac = new Set([4, 5, 6]);
  const Bc = new Set([1, 5, 6]);

  // Toggle set membership display
  const events = [
    { name: 'A', set: A, color: '#3b82f6', desc: '{1,2,3}' },
    { name: 'B', set: B, color: '#10b981', desc: '{2,3,4}' },
  ];

  const showA = selected.has('A'), showB = selected.has('B');
  const toggle = (name) => setSelected(prev => {
    const next = new Set(prev);
    next.has(name) ? next.delete(name) : next.add(name);
    return next;
  });

  // Compute sigma-algebra generated by selected events
  const genSets = [new Set(), new Set(omega)];
  if (showA) { genSets.push(A); genSets.push(Ac); }
  if (showB) { genSets.push(B); genSets.push(Bc); }
  if (showA && showB) {
    const inter = new Set([...A].filter(x => B.has(x)));
    const union = new Set([...A, ...B]);
    const AminB = new Set([...A].filter(x => !B.has(x)));
    const BminA = new Set([...B].filter(x => !A.has(x)));
    [inter, union, AminB, BminA,
      new Set([...Ac].filter(x => !B.has(x))),
      new Set([...Bc].filter(x => !A.has(x))),
      new Set([...Ac].filter(x => Bc.has(x))),
    ].forEach(s => genSets.push(s));
  }

  // Deduplicate sets
  const uniqueSets = [];
  const seen = new Set();
  for (const s of genSets) {
    const key = [...s].sort().join(',');
    if (!seen.has(key)) { seen.add(key); uniqueSets.push({ set: s, key }); }
  }

  return (
    <div className="my-8 rounded-xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-900/50">
      <h3 className="mb-1 text-base font-bold text-gray-800 dark:text-gray-200">
        σ-Algebra Generated by Events
      </h3>
      <p className="mb-3 text-sm text-gray-500 dark:text-gray-400">
        <InlineMath math="\Omega = \{1,2,3,4,5,6\}" /> (die roll). Select events to see the generated σ-algebra.
      </p>
      {/* Venn diagram */}
      <svg viewBox="0 0 320 180" className="w-full max-w-sm rounded-lg bg-gray-50 dark:bg-gray-800 border border-gray-100 dark:border-gray-700 mb-4">
        <rect x={10} y={10} width={300} height={160} rx={8} fill="none" stroke="#9ca3af" strokeWidth={1.5} />
        <text x={290} y={25} fontSize={11} fill="#6b7280" textAnchor="end">Ω</text>
        {showA && <ellipse cx={125} cy={90} rx={75} ry={55} fill="rgba(59,130,246,0.15)" stroke="#3b82f6" strokeWidth={2} />}
        {showB && <ellipse cx={195} cy={90} rx={75} ry={55} fill="rgba(16,185,129,0.15)" stroke="#10b981" strokeWidth={2} />}
        {[1,2,3,4,5,6].map((n, i) => {
          const positions = [{x:90,y:75},{x:148,y:70},{x:150,y:110},{x:200,y:80},{x:255,y:75},{x:255,y:110}];
          const inA = A.has(n), inB = B.has(n);
          const color = inA && inB ? '#7c3aed' : inA ? '#3b82f6' : inB ? '#10b981' : '#6b7280';
          return (
            <text key={n} x={positions[i].x} y={positions[i].y} fontSize={14} fill={color} fontWeight="600" textAnchor="middle">{n}</text>
          );
        })}
        {showA && <text x={75} y={85} fontSize={11} fill="#2563eb" fontWeight="600">A</text>}
        {showB && <text x={245} y={85} fontSize={11} fill="#059669" fontWeight="600">B</text>}
      </svg>
      <div className="mb-3 flex gap-3">
        {events.map(({ name, color }) => (
          <button key={name} onClick={() => toggle(name)}
            style={{ borderColor: color, backgroundColor: selected.has(name) ? color : 'transparent', color: selected.has(name) ? 'white' : color }}
            className="rounded-lg border-2 px-4 py-1 text-sm font-bold transition-colors">
            {name} = {events.find(e => e.name === name)?.desc}
          </button>
        ))}
      </div>
      <div>
        <p className="text-xs font-semibold text-gray-600 dark:text-gray-400 mb-2">
          σ({selected.size === 0 ? '∅' : [...selected].join(',')}) has {uniqueSets.length} sets:
        </p>
        <div className="flex flex-wrap gap-1.5">
          {uniqueSets.map(({ set, key }) => (
            <span key={key} className="rounded bg-indigo-50 dark:bg-indigo-900/20 px-2 py-0.5 text-xs font-mono text-indigo-700 dark:text-indigo-300">
              {set.size === 0 ? '∅' : set.size === 6 ? 'Ω' : `{${[...set].sort().join(',')}}`}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

export default function SigmaAlgebrasSection() {
  return (
    <div className="space-y-8">
      <SigmaAlgebraViz />

      <DefinitionBlock
        label="Definition 6.1.1"
        title="σ-Algebra and Measure Space"
        definition={
          "A σ-algebra $\\mathcal{F}$ on a set $\\Omega$ is a collection of subsets satisfying: " +
          "(1) $\\Omega \\in \\mathcal{F}$; " +
          "(2) if $A \\in \\mathcal{F}$, then $A^c \\in \\mathcal{F}$ (closed under complements); " +
          "(3) if $A_1, A_2, \\ldots \\in \\mathcal{F}$, then $\\bigcup_{i=1}^\\infty A_i \\in \\mathcal{F}$ (closed under countable unions). " +
          "A measure space is a triple $(\\Omega, \\mathcal{F}, \\mu)$ where $\\mu: \\mathcal{F} \\to [0,\\infty]$ is a measure: " +
          "$\\mu(\\emptyset) = 0$ and $\\mu(\\bigcup_{i=1}^\\infty A_i) = \\sum_{i=1}^\\infty \\mu(A_i)$ for disjoint sets $A_i$."
        }
        notation={
          "The Borel σ-algebra $\\mathcal{B}(\\mathbb{R})$ is the smallest σ-algebra containing all open intervals. " +
          "Lebesgue measure $\\lambda$ on $(\\mathbb{R}, \\mathcal{B}(\\mathbb{R}))$ satisfies $\\lambda([a,b]) = b-a$."
        }
      />

      <DefinitionBlock
        label="Definition 6.1.2"
        title="Measurable Functions"
        definition={
          "A function $f: (\\Omega, \\mathcal{F}) \\to (\\mathbb{R}, \\mathcal{B}(\\mathbb{R}))$ is measurable if " +
          "$f^{-1}(B) \\in \\mathcal{F}$ for every $B \\in \\mathcal{B}(\\mathbb{R})$. " +
          "Equivalently, $\\{\\omega: f(\\omega) \\leq c\\} \\in \\mathcal{F}$ for all $c \\in \\mathbb{R}$. " +
          "Continuous functions are measurable; monotone functions are measurable; " +
          "pointwise limits of measurable functions are measurable."
        }
      />

      <TheoremBlock
        label="Theorem 6.1.1"
        title="Carathéodory Extension Theorem"
        statement={
          "Let $\\mathcal{A}$ be an algebra on $\\Omega$ and $\\mu_0: \\mathcal{A} \\to [0,\\infty]$ be a pre-measure. " +
          "Then $\\mu_0$ extends to a measure $\\mu$ on the σ-algebra $\\sigma(\\mathcal{A})$ generated by $\\mathcal{A}$. " +
          "If $\\mu_0$ is σ-finite, the extension is unique."
        }
        proof={
          "Define the outer measure $\\mu^*(A) = \\inf\\{\\sum_i \\mu_0(A_i): A \\subseteq \\bigcup_i A_i, A_i \\in \\mathcal{A}\\}$. " +
          "Show $\\mu^*$ is an outer measure. Apply Carathéodory's criterion: $A$ is $\\mu^*$-measurable iff " +
          "$\\mu^*(E) = \\mu^*(E \\cap A) + \\mu^*(E \\cap A^c)$ for all $E$. The $\\mu^*$-measurable sets form a σ-algebra containing $\\mathcal{A}$."
        }
      />

      <ExampleBlock title="Constructing Lebesgue Measure">
        <p className="mb-2 text-gray-700 dark:text-gray-300">
          Start with the pre-measure on the algebra of finite unions of intervals:
          <InlineMath math="\mu_0([a,b]) = b - a" />.
          Carathéodory extends this to the Borel σ-algebra, giving Lebesgue measure.
          Key properties:
        </p>
        <BlockMath math="\lambda(\{x\}) = 0, \quad \lambda(\mathbb{Q}) = 0, \quad \lambda([0,1]) = 1" />
        <p className="text-sm text-gray-600 dark:text-gray-400">
          The rationals, though dense, have measure zero — this is why Riemann-integrable functions that
          differ on a countable set have the same Riemann integral.
        </p>
      </ExampleBlock>

      <WarningBlock title="Not All Subsets Are Measurable">
        <p>
          The Axiom of Choice implies the existence of non-measurable sets (Vitali sets). This is
          why we cannot assign a consistent notion of length to <em>every</em> subset of
          <InlineMath math="\mathbb{R}" /> — the σ-algebra structure restricts which sets get a measure.
          In practice, all sets encountered in analysis and probability are Borel or Lebesgue measurable.
          The existence of non-measurable sets is a foundational curiosity, not an obstacle for applications.
        </p>
      </WarningBlock>

      <PythonCode
        title="Measure Theory Concepts in Python"
        code={`import numpy as np

# ── Illustrate sigma-algebra properties ───────────────────────────────────
class SigmaAlgebra:
    """Simple sigma-algebra on finite omega."""
    def __init__(self, omega, sets):
        self.omega = set(omega)
        self.sets = sets
        self._verify()

    def _verify(self):
        # Check: Omega in F
        assert self.omega in [frozenset(s) for s in self.sets], "Omega not in F"
        # Check: empty set in F
        assert frozenset() in [frozenset(s) for s in self.sets] or set() in self.sets
        print("Sigma-algebra verified (finite case)")

    def measure(self, A, prob_fn):
        """Assign probability to event A using probability function."""
        return prob_fn(A)

omega = {1, 2, 3, 4, 5, 6}
# Power set sigma-algebra (for finite Omega)
from itertools import chain, combinations
power_set = list(chain.from_iterable(combinations(omega, r) for r in range(len(omega)+1)))
F = [set(s) for s in power_set]
F_frozen = [frozenset(s) for s in power_set]

print(f"Power set |F| = {len(F)} = 2^{len(omega)}")

# Uniform measure on die
prob = lambda A: len(A) / len(omega)

A = {1, 2, 3}  # P(first half)
print(f"P({{1,2,3}}) = {prob(A):.4f}")
print(f"P(complement) = {prob(omega - A):.4f}")

# ── Borel sets illustration ────────────────────────────────────────────────
# On R, intervals generate the Borel sigma-algebra
# Check: intersection of measurable sets is measurable
def lebesgue_measure(a, b):
    """Length of interval [a,b]."""
    return max(0, b - a)

intervals = [(0, 1), (0.5, 1.5), (0.3, 0.7)]
print("\\nLebesgue measures of intervals:")
for a, b in intervals:
    print(f"  λ([{a}, {b}]) = {lebesgue_measure(a, b)}")

# Countable additivity illustration
# [0,1] = disjoint union of [k/n, (k+1)/n]
n = 100
total = sum(lebesgue_measure(k/n, (k+1)/n) for k in range(n))
print(f"\\nCountable additivity check: sum of {n} sub-intervals = {total:.6f}")`}
      />
    </div>
  );
}
